[package]
name = "fallingsand"
version = "0.1.0"
authors = ["Milo Wheeler <milowheeler@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.33"
rand = "0.7"
